name: Release Build

on:
  workflow_dispatch:
  push:
    tags:
      - '*'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: 11
        cache: 'gradle'
    - name: Prepare Android keystore
      run: echo ${{ secrects.ENCODEDKEYSTORE }} | base64 --decode >> ${HOME}/keystore.jks
    - name: Download dependencies
      run: ./gradlew androidDependencies
    - name: Build release
      run: ./gradlew bundleRelease
      env:
        KEYSTORE: ${{ HOME }}/keystore.jks
        KEYSTORE_PASSWORD: ${{ secrets.KEYSTOREPASSWORD }}
        KEY_ALIAS: ${{ secrets.KEYALIAS }}
        KEY_PASSWORD: ${{ secrets.KEYPASSWORD }}
    - name: Upload Android Release to Play Store
      uses: r0adkll/upload-google-play@v1
      with:
        serviceAccountJsonPlainText: ${{ secrets.SERVICEACCOUNT }}
        packageName: de.szalkowski.activitylauncher
        releaseFiles: ActivityLauncherApp/release/*.aab
        track: beta
        whatsNewDirectory: whatsnew

